name: lints, tests, building
run-name: sidebar changes
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install node-modules
        run: npm install --force
        if: always()
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting scss
        run: npm run lint:scss
        if: always()
      - name: unit tests
        run: npm run unit
        if: always()
      - name: storybook build
        run: npm run storybook:build
        if: always()
      - name: screenshot tests
        run: npm run screenshot:ci
        if: always()


