name: lints, tests, building
run-name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: clone project
        uses: actions/checkout@v3
      - name: install node-modules
        run: npm install --force
        if: always()
      - name: linting scss
        run: npm run lint:scss
        if: always()
      - name: unit tests
        run: npm run unit
        if: always()
      - name: storybook tests
        run: npm run srbk:build
        if: always()
#      - name: screenshot tests
#        run: npm run loki:ci
#      if: always()


