name: lints, tests, building
run-name: testing build:dev
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install node-modules
        run: npm install --force
      - name: build production project
        run: npm run build:dev
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: unit tests
        run: npm run unit
      - name: storybook build
        run: npm run storybook:build
      - name: screenshot tests
        run: npm run screenshot:ci

